
    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    

    '***************************************************
    'Function maps
    '***************************************************
    function RBSFM_getFunctionsForFile(filename)
  map = {
    "TestUtils":RBSFM_getFunctions_TestUtils 
    "test_LegacyIntegration":RBSFM_getFunctions_test_LegacyIntegration 
  } 
  return map[filename]
end function

function RBSFM_getFunctions_TestUtils()
  return {
    "AddTestUtils":AddTestUtils 
    "TU_MakeTestUtils":TU_MakeTestUtils 
    "TU_SayHello":TU_SayHello 
  } 

end function

function RBSFM_getFunctions_test_LegacyIntegration()
  return {
    "testSuite_LegacyIntegration":testSuite_LegacyIntegration 
    "LegacyIntegrationTestSuite_SetUp":LegacyIntegrationTestSuite_SetUp 
    "testCase_LegacyIntegration_simpleResult":testCase_LegacyIntegration_simpleResult 
    "testCase_LegacyIntegration_multipleAsserts":testCase_LegacyIntegration_multipleAsserts 
  } 

end function

function RBSFM_getFilenames()
  return [
    "TestUtils", 
    "test_LegacyIntegration", 
  ] 
end function




    function RBSFM_getRuntimeConfig()
        return {
          "failFast": false
          "showOnlyFailures": false
          "rooibosPreprocessorVersion": 1.0.1
          }
    end function
    

    function RBSFM_getPreprocessorVersion()
        return "1.0.1"
    end function
    

    '***************************************************
    ' Unit test suites defitintions
    '***************************************************
    

    function RBSFM_getTestSuitesForProject()
        return [
        
      ]
    end function


    function RBSFM_getIgnoredTestInfo()
        return {
          "count": 0
          "items":[
        
      ]}
    end function



    '***************************************************
    ' This file is generated by rooibos. DO NOT EDIT. RTM please :)
    ' ***************************************************
    