namespace tests

  @SGNode("bitmovinPlayerCollector")
  @suite
  class BitmovinPlayerCollectorTests extends rooibos.BaseTestSuite

    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    @describe("BitmovinPlayerCollector")
    '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    protected override function beforeEach()
      ' NOTE: Cannot mock license calls right now because the components in this project are not
      ' based on Brighterscript classes. Citation from the official Rooibos docs:
      ' "You cannot stub node methods. If there is no . reference to a method (via an
      ' associated array style object), then Rooibos cannot mock it."
      ' https://github.com/rokucommunity/rooibos/blob/master/docs/index.md#nuances-of-testing-nodes

      'bs:disable-next-line
      initializeAnalytics()

      m.mockPlayer = {
        currentTime: 1447
        FindNode: function(nodeName as string)
          print "FindNode stub: tried to find node '";nodeName; "' on mockPlayer"

          if nodeName = "MainVideo" then return {
            height: 1080
            width: 1920
          }

          print "No mock for node in place - returning invalid"
          return invalid
        end function
        callFunc: function(functionName as string, arg as dynamic)
          print "callFunc stub: tried to invoke function '"; functionName; "' with arg '";arg;"' on mockPlayer"
          return invalid
        end function
        unobserveFieldScoped: function(fieldName as string)
          print "unobserveFieldScoped stub: tried to unobserve field '";fieldName;"' on mockPlayer"
        end function
      }

      m.node.player = m.mockPlayer
    end function

    @it("should extract the player key from the channel manifest with valid parameters")
    function _()
      manifestData = { "bitmovin_player_license_key": "dummyKeyValue" }
      appInfo = getMockedAppInfoWithPlayerKeyData(manifestData)
      expectedPlayerKey = manifestData.bitmovin_player_license_key

      'bs:disable-next-line
      extractedPlayerKey = getPlayerKeyFromManifest(appInfo)

      m.AssertEqual(extractedPlayerKey, expectedPlayerKey)
    end function

    @it("should extract the player key from the channel manifest with invalid parameters")
    function _()
      appInfo = invalid

      'bs:disable-next-line
      bitmovinPlayerKey = getPlayerKeyFromManifest(appInfo)

      m.AssertInvalid(bitmovinPlayerKey)
    end function

    @it("should be able to set the analytics config with valid parameters")
    function _()
      analyticsConfig = { "customDataTest": "customData" }

      'bs:disable-next-line
      isAnalyticsConfigSet = setAnalyticsConfig(analyticsConfig)

      m.AssertTrue(isAnalyticsConfigSet)
    end function

    @it("should return invalid when setting the analytics config to 'invalid'")
    function _()
      analyticsConfig = invalid

      'bs:disable-next-line
      isAnalyticsConfigSet = setAnalyticsConfig(analyticsConfig)

      m.AssertInvalid(isAnalyticsConfigSet)
    end function

    @it("should expose the error data to the user")
    function _()
      expectedErrorCode = 1447
      expectedErrorMessage = "Test error message"

      m.mockPlayer.error = {
        code: expectedErrorCode,
        message: expectedErrorMessage
      }

      m.stubCall(m.node.collectorCore.callFunc, invalid)
      m.stubCall(m.node.collectorCore.unobserveFieldScoped, invalid)

      'bs:disable-next-line
      onError()

      m.AssertNotInvalid(m.node.top.currentError)
      m.AssertEqual(m.node.top.currentError.errorCode, expectedErrorCode)
      m.AssertEqual(m.node.top.currentError.errorMessage, expectedErrorMessage)
    end function

    @it("should apply user modifications when sending an error sample")
    function _()
      originalPlayerMockError = {
        code: 1000
        message: "ORIGINAL_PLAYER_ERROR"
      }

      m.mockPlayer.error = originalPlayerMockError
      m.node.top.observeField("currentError", "modifyErrorData")

      'bs:disable-next-line
      onError()

      m.assertEqual(m.node.top.currentError.errorCode, 1001)
      m.assertEqual(m.node.top.currentError.errorMessage, "ORIGINAL_PLAYER_ERROR-MODIFIED")
    end function

  end class
end namespace

function modifyErrorData(errorEvent)
  errorData = errorEvent.getData()

  modifiedError = {
    errorcode: errorData.errorcode + 1
    errormessage: errorData.errormessage + "-MODIFIED"
  }

  m.top.currentError = modifiedError
end function

'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
'Mock Data
'+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

function getMockedAppInfoWithPlayerKeyData(manifestData)
  mockAppInfo = {}
  'mimic behaviour of roAppInfo's getValue() function
  mockAppInfo.mockManifestData = manifestData
  mockAppInfo.getValue = function(key)
    if m.mockManifestData[key] <> invalid
      value = m.mockManifestData[key]
    else
      value = ""
    end if

    return value
  end function

  return mockAppInfo
end function
