namespace tests

  @SGNode("nativePlayerCollector")
  @suite
  class NativePlayerCollectorTests extends rooibos.BaseTestSuite

    @describe("Test for the Native Player Collector")

    protected override function beforeEach()
      'bs:disable-next-line
      initializeAnalytics()

      m.mockPlayer = {
        position: 1447
        height: 1080
        width: 1920
        duration: 85
        unobserveFieldScoped: function(fieldName as string)
          print "unobserveFieldScoped stub: tried to unobserve field '";fieldName;"' on Native mockPlayer"
        end function
      }

      m.node.player = m.mockPlayer
    end function

    protected override function afterEach()
      m.cleanStubs()
      m.cleanMocks()
    end function

    @it("setAnalyticsConfig with valid params - returns true")
    @Params({ "customDataTest": "customData" })
    function _(analyticsConfig)
      'bs:disable-next-line
      isAnalyticsConfigSet = setAnalyticsConfig(analyticsConfig)
      m.AssertTrue(isAnalyticsConfigSet)
    end function


    @it("setAnalyticsConfig with invalid params - returns invalid")
    @Params(invalid)
    function _(analyticsConfig)
      'bs:disable-next-line
      isAnalyticsConfigSet = setAnalyticsConfig(analyticsConfig)
      m.AssertInvalid(isAnalyticsConfigSet)
    end function

    @it("should expose the error data to the user")
    function _()
      expectedErrorCode = 1447
      expectedErrorMessage = "Test error message"

      m.mockPlayer.errorCode = expectedErrorCode
      m.mockPlayer.errorMsg = expectedErrorMessage

      originalCollectorCore = m.node.collectorCore

      m.stubCall(m.node.collectorCore.callFunc, invalid)
      m.stubCall(m.node.collectorCore.unobserveFieldScoped, invalid)

      'bs:disable-next-line
      onError()
      errorEventData = m.node.top.error

      m.AssertNotInvalid(errorEventData)
      m.AssertEqual(errorEventData.error.code, expectedErrorCode)
      m.AssertEqual(errorEventData.error.message, expectedErrorMessage)

      m.node.collectorCore = originalCollectorCore
    end function

    @it("should apply user modifications when sending an error sample")
    function _()
      originalPlayerMockErrorCode = 1000
      originalPlayerMockErrorMessage = "ORIGINAL_PLAYER_ERROR"

      m.mockPlayer.errorCode = originalPlayerMockErrorCode
      m.mockPlayer.errorMsg = originalPlayerMockErrorMessage
      m.node.top.observeField("error", "modifyNativeErrorData")

      'bs:disable-next-line
      onError()
      errorEventData = m.node.top.error

      m.assertEqual(errorEventData.error.code, 1001)
      m.assertEqual(errorEventData.error.message, "ORIGINAL_PLAYER_ERROR-MODIFIED")
      m.assertEqual(errorEventData.error.severity, "INFO")
    end function

  end class

end namespace

function modifyNativeErrorData(errorEvent)
  errorData = errorEvent.getData()

  errorData.error.message = errorData.error.message + "-MODIFIED"
  errorData.error.code = errorData.error.code + 1
  errorData.error.severity = "INFO"

  m.top.error = errorData
end function