namespace tests

  @SGNode("collectorCore")
  @suite("SsaiService")
  class SsaiServiceTests extends rooibos.BaseTestSuite
    protected override function beforeEach()
      'bs:disable-next-line
      initializeAnalytics()
      'bs:disable-next-line
      setupSsaiService()
    end function

    @describe("getSsaiAdSample")
    @it("should set the elapsed time to -1 if no timer is active")
    function _()
      expectedTime = -1

      'bs:disable-next-line
      sample = getSsaiAdSample()

      m.assertEqual(sample.timeSinceAdStartedInMs, expectedTime)
    end function

    @it("should set the elapsed time since adStart if an ad is in progress")
    function _()
      'bs:disable-next-line
      adBreakStart()
      'bs:disable-next-line
      adStart()

      'bs:disable-next-line
      sample = getSsaiAdSample()

      m.assertTrue(sample.timeSinceAdStartedInMs >= 0)
    end function

    @describe("adQuartileFinished")
    @it("returns invalid if a quartile has already been reported")
    function _()
      m.asserTrue(false)
    end function

    @it("returns invalid if no ad is in progress")
    function _()
      m.asserTrue(false)
    end function

    @it("sets the correct prop on the sample for each adQuartile type")
    function _()
      m.asserTrue(false)
    end function

    @it("sets the correct prop on the sample for failedBeaconUrls")
    function _()
      m.asserTrue(false)
    end function

    @it("does not set flags on sample if a quartile is reported twice during an ad")
    function _()
      m.asserTrue(false)
    end function

  end class

end namespace
